### ISSUE TITLE
More recent DCaPSTInstall.msi not working with APSIM 7.8

### ISSUE THREAD

**Issue by smuel-tylor** [QAAFI/DCaPST#14]
I'm revisiting work I did in mid 2019 with the 2018 version of DCaPST. Because I'd lost a laptop in the interim I re-installed from the current master but found that running simulations from APSIM was not resulting in any differences between models with different photosynthetic modifications using any of the example files or the simulations I have built.

The installer was implementing the changes to dll folders etc that were expected, and APSIM was running without throwing errors, but APSIM output was the same for all models - my guess is that it's running standard functions and bypassing the DCaPST functions for some reason.

Re-installing using the 2018 DCaPSTInstall.msi has fixed the issue and I now have a working version again.

**Comment by MikeStower** [comment]
Between now and 2018 DCaPST has been almost entirely rewritten to be included in APSIM directly, and this repository is now legacy code. The maintained version of the DCaPST source can be found [here](https://github.com/APSIMInitiative/APSIMClassic/tree/master/Model/DCaPST), and is automatically bundled with APSIM 7.10. Because of this, more recent versions of DCaPST do not require an installer, and the installer has not been maintained.

If you want to use the latest version of DCaPST, I recommend switching to APSIM 7.10. If you need to keep using 7.8 for other reasons, either manually compile the DCaPST code linked above (easiest to do through the DCaPST.sln), or do a separate install of 7.10 and copy the dll as required. 

In either case, newer versions of DCaPST use updated manager scripts and will need to be updated in your simulations to use the library. Examples of more recent manager scripts can be found [here](https://github.com/APSIMInitiative/APSIMClassic/tree/master/Model/DCaPST/Scripts).

**Comment by MikeStower** [comment]
Also keep in mind that there have been some changes / fixes to the model itself in that time. If your current work requires the same version of DCaPST you used previously, stick with the 2018 installer and 7.8.
